apiVersion: kuttl.dev/v1beta1
kind: TestSuite
crdDir: ./tests/_build/crds/
artifactsDir: ./tests/_build/artifacts/
kindContainers:
  - localhost/local/bestie-operator:e2e
commands:
  - command: kubectl apply -f ./tests/_build/manifests/bestie-operator.yaml
  - command: kubectl wait --timeout=5m --for=condition=available deployment l5-operator-controller-manager -n l5-operator-system
  - command: kubectl get pods -n l5-operator-system
  - command: sleep 60s
testDirs:
  - ./tests/e2e/
timeout: 150