name: "End-to-end tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kube-version:
        - "1.19"
        - "1.23"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0

    - name: "Install Kuttl"
      run: ./hack/install-kuttl.sh
    
    - name: "Install Kustomize"
      run: ./hack/setup-kustomize.sh
    
    - name: "Install PGO"
      run: ./hack/install-pgo.sh
    
    - name: "Install Operator-sdk"
      run: make operator-sdk

    - name: "run tests"
      env:
        KUBE_VERSION: ${{ matrix.kube-version }}
      run: make prepare-e2e e2e KUBE_VERSION=$KUBE_VERSION